### ISSUE TITLE
issue with the 'start' and 'end' in the match_type_info in outputBam

### ISSUE THREAD

**Issue by ShengyaoChen** [fulcrumgenomics/fg-idprimer#11]
I noticed that there might be an issue with the ‘start’ and ‘end’ in the match_type_info for the gapped alignment. From the description: the ‘start’ and the ‘end’ are the offset from the start of the read where the match starts and ends.
Here is an example:
![f3tagissue](https://user-images.githubusercontent.com/20647165/50986109-c7cbb700-14ba-11e9-8384-bd697027ec30.png)

**In f3 tag, the start and the end is “1,23”, suggesting that they are calculated based on the offset from the primer where the match starts and ends**. Can you look into it to see if there is an issue in reporting the start/end in the match_type_info?

**Comment by ShengyaoChen** [comment]
Hi Nils @nh13 

To follow up with my observation. I think that the issue lies in this function in PrimerMatcher.scala:
``` /** Returns a primer match given a set of alignments and primers. */
  def getBestGappedAlignment(primersAndAlignments: Seq[(Primer, Alignment)]): Option[GappedAlignmentPrimerMatch] = {
    if (primersAndAlignments.isEmpty) None
    else {
      primersAndAlignments
        .sortBy { case (_, alignment) => -alignment.normalizedScore } // get the maximum normlaized score
        .take(2) match {
          case Seq()                    =>
            unreachable("Should have found at least one.")
          case Seq((primer, alignment)) =>
            if (alignment.score < 0) None else {
              Some(GappedAlignmentPrimerMatch(primer, alignment.score, 0, alignment.queryStart, alignment.queryEnd))
            }
          case Seq((bestPrimer, bestAlignment), (_, nextAlignment)) =>
            Some {
              GappedAlignmentPrimerMatch(
                bestPrimer,
                bestAlignment.normalizedScore,
                nextAlignment.normalizedScore,
                bestAlignment.queryStart,
                bestAlignment.queryEnd)
            }
        }
    }
  }
```
 The issue here is we are returning the queryStart, which are the offset position on the Primers where the match starts, not the the offset from the start of the read where the primer match starts. And the same applies to queryEnd.

I changed the queryStart to targetStart; queryEnd to targetEnd. And I see the position of the primers on the reads are successfully identified.

![image](https://user-images.githubusercontent.com/20647165/55116034-40e2af80-50a3-11e9-931a-5b0c581f5fdb.png)


Can you confirm my observation?
Thanks very much!

**Comment by nh13** [comment]
@ShengyaoChen I think you're right, do you want to make a quick PR to fix it?

**Comment by ShengyaoChen** [comment]
@nh13 Thanks for the response! Yes, I have made a PR.
